# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prueba.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDoubleValidator, QValidator


class Ui_Ploter(object):
    def setupUi(self, Ploter):
        Ploter.setObjectName("Ploter")
        Ploter.resize(485, 297)
        self.centralwidget = QtWidgets.QWidget(Ploter)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")   # 0 es primer orden
        self.comboBox.addItem("")   # 1 es segundo orden
        self.comboBox.addItem("")   # 2 es orden superior
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.LabelL = QtWidgets.QLabel(self.centralwidget)
        self.LabelL.setObjectName("LabelL")
        
        self.horizontalLayout.addWidget(self.LabelL)
        
        self.lineEditL = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditL.setObjectName("lineEditL")
        
        self.horizontalLayout.addWidget(self.lineEditL)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.labelR = QtWidgets.QLabel(self.centralwidget)
        self.labelR.setObjectName("labelR")
        
        self.horizontalLayout_2.addWidget(self.labelR)
        
        self.lineEditR = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditR.setObjectName("lineEditR")
        
        self.horizontalLayout_2.addWidget(self.lineEditR)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Ploter.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ploter)
        QtCore.QMetaObject.connectSlotsByName(Ploter)

    def retranslateUi(self, Ploter):
        _translate = QtCore.QCoreApplication.translate
        Ploter.setWindowTitle(_translate("Ploter", "UwU"))
        self.comboBox.setItemText(0, _translate("Ploter", "Pimer orden"))
        self.comboBox.setItemText(1, _translate("Ploter", "Segundo orden"))
        self.comboBox.setItemText(2, _translate("Ploter", "Orden superior"))
        self.comboBox.activated.connect(self.getIndex)
        
        self.LabelL.setText(_translate("Ploter", "Cero:"))
        
        self.labelR.setText(_translate("Ploter", "Polos:"))
        
        self.pushButton.setText(_translate("Ploter", "PushButton"))
        self.floatvalidator()
        self.lineEditL.returnPressed.connect(lambda: print(self.lineEditL.text()))
        self.lineEditR.returnPressed.connect(lambda: print(self.lineEditR.text()))
        self.pushButton.clicked.connect(lambda: print("nashe"))
        
    
    
    #Lee la el index y cambia el valor del index
    def getIndex(self):
        if self.comboBox.currentIndex() == 1:
            self.LabelL.setText("Wo:")
            self.labelR.setText("ξ:")
        elif self.comboBox.currentIndex() == 2:
            self.LabelL.setText("Numerador:")
            self.labelR.setText("Denominador:")
        else:
            self.LabelL.setText("Cero:")
            self.labelR.setText("Polo:")
        self.updateSize()
        
    
    def updateSize(self):
        self.labelR.adjustSize()
        self.LabelL.adjustSize()
    
    def floatvalidator(self):
        self.onlyfloat = QDoubleValidator(-1000000000,1000000000,1000000000)
        self.lineEditL.setValidator(self.onlyfloat)
        self.lineEditR.setValidator(self.onlyfloat)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ploter = QtWidgets.QMainWindow()
    ui = Ui_Ploter()
    ui.setupUi(Ploter)
    Ploter.show()
    sys.exit(app.exec_())
